### ISSUE TITLE
Background doesn't cover the whole editor...

### ISSUE THREAD

**Issue by francisceril** [jchouse/spacegray-atom-dark-ui#1]
I'm not sure if it is intended to work like this. I have space gray-atom-dark-ui and space gray-atom-dark-syntax installed and activated. The background only covers 50% of the width of the editor and just the lines with text on it as shown on my attached screenshot.
![screen shot 2016-10-22 at 8 42 53 pm](https://cloud.githubusercontent.com/assets/5759665/19621331/24d75a9a-9898-11e6-9b92-03a385a589ff.png)

The issue persist regardless of syntax theme I use so I think it's an issue with the theme.

**Comment by jchouse** [comment]
Yeah, I know about it:) this is a bug in early builds of webkit. In the latest version of Chrome Canary, it is gone, I think the atom will soon be corrected.
